#!/usr/bin/env python3
"""Generate English completion rewards from Wiki reward links and EID entity IDs.

Never reads the old reward catalog or generated unlocks. Non-entity rewards use
the Wiki English title; exceptional starting abilities retain explicit labels.
"""
from pathlib import Path
import argparse
import json
import re

from build_achievements import parse_rows, reward_entities_from_cell
from build_unlocks import completion_achievement_ids
from crawl_effects import CACHE, EN_SOURCES, fetch, parse_pack

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'tools/achievement_rewards_en.json'
NON_ENTITY_NAMES = {
    175: '-0- Baby',  # Wiki has only "O"; retain its co-op baby classification.
    191: 'Keeper now holds…A Penny!',
}


def build_entries(required, rows, entities):
    entries = {}
    for aid in required:
        if aid not in rows:
            raise RuntimeError(f'Wiki HTML is missing achievement #{aid}')
        cells = rows[aid]
        rewards = reward_entities_from_cell(cells[5])
        names = []
        for reward in rewards:
            key = (reward['entityType'], reward['entityId'])
            if key not in entities:
                raise RuntimeError(f'Achievement #{aid}: missing English EID entity {key}')
            names.append(entities[key]['enName'])
        if names:
            name = ' / '.join(names)
            if aid in (236, 237):
                name = 'Keeper holds ' + name
        elif aid in NON_ENTITY_NAMES:
            name = NON_ENTITY_NAMES[aid]
        else:
            # Titles are only a fallback for rewards without an entity link.
            lines = [line.strip() for line in str(cells[1]['text']).splitlines()]
            english = [line for line in lines if re.search(r'[A-Za-z]', line)
                       and not re.search(r'[\u3400-\u9fff]', line)]
            if len(english) != 1:
                raise RuntimeError(f'Achievement #{aid}: no unique non-entity English title: {lines}')
            name = english[0]
        if not name or re.search(r'[\u3400-\u9fff]', name):
            raise RuntimeError(f'Achievement #{aid}: invalid English reward {name!r}')
        entries[str(aid)] = name
    return entries


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('html', type=Path, help='saved Huiji full achievement HTML')
    parser.add_argument('--completion-html', type=Path, required=True,
                        help='saved Project:存档/成就 HTML to select completion-mark IDs')
    parser.add_argument('--refresh-eid', action='store_true')
    parser.add_argument('--output', type=Path, default=OUT)
    args = parser.parse_args()
    entities = {}
    for pack, url in EN_SOURCES:
        path = CACHE / f'{pack.replace("+", "plus")}_en_us.lua'
        for row in parse_pack(pack, fetch(url, path, args.refresh_eid), 'en'):
            entities[(row['category'], row['id'])] = row
    entries = build_entries(completion_achievement_ids(args.completion_html),
                            parse_rows(args.html), entities)
    payload = {'version': 2, 'purpose': 'Generated by tools/build_achievement_rewards_en.py from Wiki reward entity links and EID English names.',
               'entries': entries}
    args.output.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + '\n', 'utf-8')
    print(json.dumps({'englishRewards': len(entries)}, ensure_ascii=False))


if __name__ == '__main__':
    main()
