#!/usr/bin/env python3
"""Compile built-in recommendation JSON sources into one browser-loadable JS file.

The browser never fetches JSON at runtime. This keeps GitHub Pages, FTP/static
hosting, and file:// local previews compatible while preserving JSON as the
human-editable source format.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "tools"
MANIFEST = TOOLS / "recommendation_profiles.json"
OUT = ROOT / "data" / "recommendation_profiles.js"
ALLOWED = {"normal", "recommended", "strong"}


def read_json(path: Path):
    return json.loads(path.read_text("utf-8"))


def main() -> None:
    manifest = read_json(MANIFEST)
    profiles = []
    seen_ids = set()

    for item in manifest.get("profiles", []):
        pid = item["id"]
        if pid in seen_ids:
            raise RuntimeError(f"duplicate profile id: {pid}")
        seen_ids.add(pid)

        rec = read_json(TOOLS / item["characterBossFile"])
        challenge = read_json(TOOLS / item["challengeFile"])

        character_boss = []
        for entry in rec.get("entries", []):
            if set(entry) != {"characterId", "bossId", "priority"}:
                raise RuntimeError(f"invalid character/Boss entry in {pid}: {entry}")
            if entry["priority"] not in ALLOWED:
                raise RuntimeError(f"invalid priority in {pid}: {entry}")
            character_boss.append(dict(entry))

        challenges = []
        for entry in challenge.get("entries", []):
            if set(entry) != {"challengeId", "priority"}:
                raise RuntimeError(f"invalid challenge entry in {pid}: {entry}")
            if entry["priority"] not in ALLOWED:
                raise RuntimeError(f"invalid challenge priority in {pid}: {entry}")
            challenges.append(dict(entry))

        profiles.append({
            "id": pid,
            "name": item.get("name") or pid,
            "description": item.get("description", ""),
            "source": item.get("source", ""),
            "defaultPriority": rec.get("defaultPriority", "normal"),
            "characterBoss": character_boss,
            "challenges": challenges,
        })

    default_id = manifest.get("defaultProfileId")
    if default_id not in seen_ids:
        raise RuntimeError(f"defaultProfileId does not exist: {default_id}")

    payload = {
        "version": int(manifest.get("version", 1)),
        "defaultProfileId": default_id,
        "profiles": profiles,
    }
    OUT.write_text(
        "// Generated by tools/build_recommendation_profiles.py. Do not edit by hand.\n"
        + "window.ISAAC_RECOMMENDATION_PROFILES = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n",
        "utf-8",
    )
    print(json.dumps({
        "profiles": len(profiles),
        "defaultProfileId": default_id,
        "characterBossEntries": sum(len(x["characterBoss"]) for x in profiles),
        "challengeEntries": sum(len(x["challenges"]) for x in profiles),
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
